model: israel-adewuyi/Astracode-1.5B
tokenizer: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
host: "0.0.0.0"
port: 63455
uvicorn-log-level: "info"
max_model_len: 16384
gpu_memory_utilization: 0.5
# gpu_memory_utilization: 0.4 # for test
