model: Qwen/Qwen2.5-7B-Instruct
# model: Qwen/Qwen2.5-3B-Instruct # for test
host: "0.0.0.0"
port: 63450
uvicorn-log-level: "info"
max_model_len: 4096
gpu_memory_utilization: 0.4
# gpu_memory_utilization: 0.47 # for test